In [10]:
import xarray as xr
import pandas as pd
import os
from pathlib import Path

# Loading data

## Load data from SSRD and temperature

In [11]:

# Load the NetCDF file
base_path = Path(os.getcwd())

file_relative = r"..\..\Data\Raw\reanalysis-era5-single-levels-timeseries-sfc7rupio5o.nc"

file_path = (base_path / file_relative).resolve()

ds = xr.open_dataset(file_path)

# Inspect the dataset first
print("=== VARIABLES ===")
print(ds.data_vars)
print("\n=== COORDINATES ===")
print(ds.coords)
print("\n=== DIMENSIONS ===")
print(ds.dims)

=== VARIABLES ===
Data variables:
    t2m      (valid_time) float32 1MB ...
    ssrd     (valid_time) float32 1MB ...

=== COORDINATES ===
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 2MB 1995-01-01 ... 2025-12-31T23:...
    latitude    float64 8B ...
    longitude   float64 8B ...

=== DIMENSIONS ===
FrozenMappingWarningOnValuesAccess({'valid_time': 271752})

In [12]:
# Convert to pandas DataFrame
df_bol = ds.to_dataframe().reset_index()

# Basic inspection
print(df_bol.head())
print(df_bol.dtypes)
print(df_bol.shape)

           valid_time         t2m  ssrd  latitude  longitude
0 1995-01-01 00:00:00  278.872528   0.0      45.5      11.25
1 1995-01-01 01:00:00  278.874054   0.0      45.5      11.25
2 1995-01-01 02:00:00  278.856934   0.0      45.5      11.25
3 1995-01-01 03:00:00  278.844604   0.0      45.5      11.25
4 1995-01-01 04:00:00  278.973236   0.0      45.5      11.25
valid_time    datetime64[ns]
t2m                  float32
ssrd                 float32
latitude             float64
longitude            float64
dtype: object
(271752, 5)

In [13]:
df_bol['SSRD_Wm2'] = df_bol['ssrd'] / 3600

df_bol['date'] = df_bol['valid_time'].dt.date
df_bol['hour'] = df_bol['valid_time'].dt.time

#rename valid_time to time
df_bol.rename(columns={'valid_time': 'time'}, inplace=True)

In [14]:
df_bol.head(15)

,time,t2m,ssrd,latitude,longitude,SSRD_Wm2,date,hour
0,1995-01-01 00:00:00,278.872528,0.0,45.5,11.25,0.000000,1995-01-01,00:00:00
1,1995-01-01 01:00:00,278.874054,0.0,45.5,11.25,0.000000,1995-01-01,01:00:00
2,1995-01-01 02:00:00,278.856934,0.0,45.5,11.25,0.000000,1995-01-01,02:00:00
3,1995-01-01 03:00:00,278.844604,0.0,45.5,11.25,0.000000,1995-01-01,03:00:00
4,1995-01-01 04:00:00,278.973236,0.0,45.5,11.25,0.000000,1995-01-01,04:00:00
5,1995-01-01 05:00:00,278.671875,0.0,45.5,11.25,0.000000,1995-01-01,05:00:00
6,1995-01-01 06:00:00,278.741455,0.0,45.5,11.25,0.000000,1995-01-01,06:00:00
7,1995-01-01 07:00:00,278.156128,0.0,45.5,11.25,0.000000,1995-01-01,07:00:00
8,1995-01-01 08:00:00,278.311646,112768.0,45.5,11.25,31.324444,1995-01-01,08:00:00
9,1995-01-01 09:00:00,278.947510,511552.0,45.5,11.25,142.097778,1995-01-01,09:00:00
10,1995-01-01 10:00:00,280.741669,941184.0,45.5,11.25,261.440002,1995-01-01,10:00:00
11,1995-01-01 11:00:00,281.133301,1185408.0,45.5,11.25,329.279999,1995-01-01,11:00:00
12,1995-01-01 12:00:00,280.680420,1215616.0,45.5,11.25,337.671112,1995-01-01,12:00:00
13,1995-01-01 13:00:00,280.691559,873088.0,45.5,11.25,242.524445,1995-01-01,13:00:00
14,1995-01-01 14:00:00,280.806580,684096.0,45.5,11.25,190.026672,1995-01-01,14:00:00

## Load SSRD Clear sky

In [15]:
# Load the NetCDF file
base_path = Path(os.getcwd())

file_relative = r"..\..\Data\Raw\cams_solar_irradiance_ts.nc"

file_path = (base_path / file_relative).resolve()

df_cs = xr.open_dataset(file_path)

In [16]:
# Convert to pandas DataFrame
df_bol_cs = df_cs.to_dataframe().reset_index()

# Basic inspection
print(df_bol_cs.columns)
print(df_bol_cs.dtypes)

Index(['time', 'altitude', 'latitude', 'longitude', 'ut_jd', 'ut_year',
       'ut_month', 'ut_day', 'ut_hour', 'ut_minute', 'ut_second', 'tst_jd',
       'tst_year', 'tst_month', 'tst_day', 'tst_hour', 'tst_minute',
       'tst_second', 'G0', 'CLEAR_SKY_GHI', 'CLEAR_SKY_BHI', 'CLEAR_SKY_DHI',
       'CLEAR_SKY_BNI', 'rely', 'GHI', 'BHI', 'DHI', 'BNI'],
      dtype='str')
time             datetime64[ns]
altitude                float64
latitude                float64
longitude               float64
ut_jd                   float64
ut_year                   int16
ut_month                   int8
ut_day                     int8
ut_hour                    int8
ut_minute                  int8
ut_second               float64
tst_jd                  float64
tst_year                  int16
tst_month                  int8
tst_day                    int8
tst_hour                   int8
tst_minute                 int8
tst_second              float64
G0                      float64
CLEAR_SKY_GHI           float64
CLEAR_SKY_BHI           float64
CLEAR_SKY_DHI           float64
CLEAR_SKY_BNI           float64
rely                    float64
GHI                     float64
BHI                     float64
DHI                     float64
BNI                     float64
dtype: object

In [17]:
# Selecting 'time', 'latitude', 'longitude', 'CLEAR_SKY_GHI', 'GHI' from df_bol_cs
df_bol_ghi = df_bol_cs[['time', 'CLEAR_SKY_GHI', 'GHI']]
df_bol_ghi.head(15)

                  time  CLEAR_SKY_GHI         GHI
0  2005-01-01 01:00:00       0.000000    0.000000
1  2005-01-01 02:00:00       0.000000    0.000000
2  2005-01-01 03:00:00       0.000000    0.000000
3  2005-01-01 04:00:00       0.000000    0.000000
4  2005-01-01 05:00:00       0.000000    0.000000
5  2005-01-01 06:00:00       0.000000    0.000000
6  2005-01-01 07:00:00       0.054937    0.054937
7  2005-01-01 08:00:00      59.074631   59.074631
8  2005-01-01 09:00:00     194.115555  194.023499
9  2005-01-01 10:00:00     307.682556  299.007507
10 2005-01-01 11:00:00     377.276642  377.276642
11 2005-01-01 12:00:00     394.554718  394.554718
12 2005-01-01 13:00:00     357.696289  357.696289
13 2005-01-01 14:00:00     270.637909  270.637909
14 2005-01-01 15:00:00     144.780121  144.780121

## Joining dataframes

In [18]:
#Drop latitude and longitude from df_s

# Join df_bol and df_selected on 'time', 'latitude', 'longitude'
df_bol_full = pd.merge(df_bol, df_bol_ghi, on=['time'], how='inner')

# select only the columns 'time', 'latitude', 'longitude', 'SSRD_Wm2', 'CLEAR_SKY_GHI', 'GHI'
df_bol_full = df_bol_full[['time', 'latitude', 'longitude', 't2m', 'SSRD_Wm2', 'CLEAR_SKY_GHI', 'GHI']]

df_bol_full.head(15)

,time,latitude,longitude,t2m,SSRD_Wm2,CLEAR_SKY_GHI,GHI
0,2005-01-01 01:00:00,45.5,11.25,273.518036,0.000000,0.000000,0.000000
1,2005-01-01 02:00:00,45.5,11.25,273.708679,0.000000,0.000000,0.000000
2,2005-01-01 03:00:00,45.5,11.25,273.617981,0.000000,0.000000,0.000000
3,2005-01-01 04:00:00,45.5,11.25,273.726379,0.000000,0.000000,0.000000
4,2005-01-01 05:00:00,45.5,11.25,273.732208,0.000000,0.000000,0.000000
5,2005-01-01 06:00:00,45.5,11.25,273.778809,0.000000,0.000000,0.000000
6,2005-01-01 07:00:00,45.5,11.25,273.141968,0.000000,0.054937,0.054937
7,2005-01-01 08:00:00,45.5,11.25,273.965393,41.955555,59.074631,59.074631
8,2005-01-01 09:00:00,45.5,11.25,275.816895,157.315552,194.115555,194.023499
9,2005-01-01 10:00:00,45.5,11.25,280.194794,261.191101,307.682556,299.007507
10,2005-01-01 11:00:00,45.5,11.25,281.352509,322.666656,377.276642,377.276642
11,2005-01-01 12:00:00,45.5,11.25,282.130127,346.951111,394.554718,394.554718
12,2005-01-01 13:00:00,45.5,11.25,282.456299,308.302216,357.696289,357.696289
13,2005-01-01 14:00:00,45.5,11.25,282.351898,228.426666,270.637909,270.637909
14,2005-01-01 15:00:00,45.5,11.25,280.991211,114.559998,144.780121,144.780121

### Saving the final dataframe

In [21]:

base_path = Path(os.getcwd())

file_relative = r"..\..\Data\Raw\df_bologna_full.parquet"

output_path = (base_path / file_relative).resolve()

df_bol_full.to_parquet(output_path, index=False)